repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'DJANGO_SETTINGS_MODULE=fithub.test_settings_sqlite uv run pytest --tb=short'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        args: []

      - id: lint
        name: lint
        entry: uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv,venv,__pycache__,.git
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        args: []

      - id: format-check
        name: format-check
        entry: bash -c 'uv run black --check . && uv run isort --check-only .'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        args: []

      - id: security
        name: security
        entry: bash -c 'uv run bandit -r . --exclude .venv,venv,__pycache__,.git || true'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        args: []
