version: "3.9"
services:
  db:
    image: postgres:16
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
